[[redirects]]
  from = "/<./>"
  to = "<https://back-rpg-3olc.vercel.app>"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/"
  [headers.values]
    Access-Control-Allow-Origin = "https://back-rpg-3olc.vercel.app"
